#!/bin/bash

echo "Content-Type: multipart/x-mixed-replace;boundary=ffmpeg"
echo "Cache-Control: no-cache"
echo "Query: $QUERY_STRING"
echo ""
ffmpeg  -i "$QUERY_STRING" -r 1 -c:v mjpeg -q:v 1 -f mpjpeg -an -
